---
- name: setup vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variable
      include_vars: vars/output_vars
    - name: Import vprofie setup Variable
      include_vars: vars/vprostacksetup
    
    - name: create vprofile ec2 key
      ec2_key:
        name: vprokey2
        region: "{{ region }}"
      register: vprokey2_out  

    - name: save prive key into file loginkey_vpro.pem
      copy:
        content: "{{ vprokey2_out.key.private_key }}" 
        dest: "./loginkey_vpro.pem" 
        mode: 0600
      when: vprokey2_out.changed
    - name: create Security group for Load balancer
      ec2_group: 
        name: vproELB-sg
        description: allow port 80 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBSG_out   
    - name: create Security group for Load balancer for test
      ec2_group: 
        name: vproStack-sg
        description: allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ vproELBSG_out }}"
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ BastionSGid }}"
      register: vproStackSG_out     
      
    - name: Update security group with its own sg id
      ec2_group: 
        name: vproStack-sg
        description: allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{ vproStackSG_out.group_id }}"
       
